---
abstract: 'Write Perl Subroutines in Other Programming Languages'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  JSON::PP: '0'
  Test::More: '0.88'
  Test::Warn: '0.23'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Inline
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  Digest::MD5: '0'
  File::Spec: '0.8'
  perl: v5.8.1
  version: '0.82'
resources:
  bugtracker: https://github.com/ingydotnet/inline-pm/issues
  homepage: https://github.com/ingydotnet/inline-pm
  repository: https://github.com/ingydotnet/inline-pm.git
version: '0.86'
x_generated_by_perl: v5.28.0
x_serialization_backend: 'YAML::Tiny version 1.73'
